BePitchAndPutt/BePitchAndPutt/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.contrib.auth.models import User
from django.contrib.auth.views import login, logout
from django.contrib.auth.decorators import login_required
from iBePitchAndPutt.views import *
from django.core.urlresolvers import reverse_lazy
from django.views.generic.base import RedirectView
from rest_framework.urlpatterns import format_suffix_patterns


urlpatterns = [
    url(r'^$', mainpage, name='home'),
    url(r'^login/$', login, name='login'),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^accounts/logout/$', logout, name='logout'),
    
    url(r'^player(\.(?P<extension>(json|xml)))?$$',PlayerList.as_view(),name='Player_list'),
    url(r'^player/(?P<pk>\d+)(\.(?P<extension>(json|xml)))?$',PlayerDetail.as_view(),name='Player_detail'),
    url(r'^player/create/$',PlayerCreate.as_view(),name='player_create'),
    
    url(r'^rules/',rules, name='rules'),
    
    url(r'^player/(?P<pkr>\d+)/match/(?P<pk>\d+)(\.(?P<extension>(json|xml)))?$',MatchDetail.as_view(),name="Match_detail"),
    url(r'^player/(?P<pk>\d+)/match/create/$',MatchCreate.as_view(),name='match_create'),
    url(r'^player/(?P<pkr>\d+)/match/(?P<pk>\d+)/edit/$',LoginRequiredCheckIsOwnerUpdateView.as_view(
        model = Match,
        form_class = MatchForm),
        name='match_edit'
        ),
    
    url(r'player/(?P<pkrr>\d+)/match/(?P<pkr>\d+)/throw/(?P<pk>\d+)(\.(?P<extension>(json|xml)))?$', ThrowDetail.as_view(), name="Throw_detail"),

    url(r'^player/(?P<pkrr>\d+)/match/(?P<pkr>\d+)/throw/(?P<pk>\d+)/edit/$',LoginRequiredCheckIsOwnerUpdateView.as_view(
        model = Throw,
        form_class = ThrowForm),
        name='throw_edit'
        ),

    url(r'^player/(?P<pkr>\d+)/match/(?P<pk>\d+)/throw/create/$',ThrowCreate.as_view(),name='throw_create'),
    
    url(r'^field(\.(?P<extension>(json|xml)))?$',FieldList.as_view(),name="Field_list"),
    url(r'^field/(?P<pk>\d+)(\.(?P<extension>(json|xml)))?$',FieldDetail.as_view(),name="Field_detail"),


    #RESTful API
    
    url(r'^api/auth/',include('rest_framework.urls', namespace='rest_framework')),
    
    url(r'^api/player/$',
        APIPlayerList.as_view(), name='player-list'),
    url(r'^api/player/(?P<pk>\d+)/$',
        APIPlayerDetail.as_view(), name='player-detail'),

    url(r'^api/field/$',
        APIPlayerList.as_view(), name='field-list'),
    url(r'^api/field/(?P<pk>\d+)/$',
        APIFieldDetail.as_view(), name='field-detail'),

    url(r'^api/match/(?P<pk>\d+)/$',
        APIMatchDetail.as_view(), name='match-detail'),

    url(r'^api/throw/(?P<pk>\d+)/$',
        APIThrowDetail.as_view(), name='throw-detail'),

    
   # url(r'^api/actualWeather/$',
    #    APIActualWeather.as_view(), name='actual_weather'),
    
]


urlpatterns = format_suffix_patterns(urlpatterns, allowed=['api','json', 'xml'])
 
   

    
    

BePitchAndPutt/iBePitchAndPutt/models.py
from	django.db	import	models
from	datetime	import	date
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db.models import Sum
import sys
import requests
import json
# Create your models here.

class Player (models.Model):
    name = models.CharField(max_length=100, blank=False)
    number_of_player = models.AutoField(primary_key=True, unique=True)
    birthdate = models.DateField()
    country = models.CharField(max_length=100)
    stateOrProvince = models.CharField(max_length=100,blank=True, null=True)
    city = models.CharField(max_length=100)
    street = models.CharField(max_length=100,blank=True, null=True)
    zipCode = models.CharField(max_length=100,blank=True, null=True)
    telephone = models.IntegerField(null = False, blank = False)
    handicap = models.FloatField(null = True, blank = True)
    user = models.ForeignKey(User, default=1)

    def __unicode__(self):
        return u'%s' % self.name
    def get_absolute_url(self):
        return reverse('Player_detail',kwargs={'pk':self.pk})


class Field(models.Model):
    FieldCode = models.IntegerField(null = False, blank = False)
    field_name = models.CharField(blank = False, null = False, max_length=100)
    stateOrProvince = models.CharField(max_length=100,blank=True, null=True)
    city = models.CharField(null = False, blank = False, max_length=100)
    street = models.CharField(max_length=100,blank=True, null=True)
    zipCode = models.CharField(max_length=100,blank=True, null=True)
    telephone = models.IntegerField(null = True, blank = True)
    url = models.URLField(blank=True, null=True)
    number_of_holes = models.IntegerField()
    par = models.IntegerField(null = False, blank = False)
    user = models.ForeignKey(User, default=1)

    def __unicode__(self):
        return u'%s' % self.field_name


class Hole (models.Model):
    field = models.ForeignKey(Field, null=False, related_name='holes')
    hole_number = models.IntegerField(null = False, blank = False)
    meters = models.IntegerField(null = False, blank = False)
    handicap_hole = models.IntegerField(null = False, blank = False)
    user = models.ForeignKey(User, default=1)
    def __unicode__(self):
        return u'%i' % self.hole_number

class WeatherConditions (models.Model):
    date = models.CharField(max_length=100,default='today')
    windSpeed = models.FloatField()
    windDirection = models.TextField()
    user = models.ForeignKey(User, default=1)

class Match (models.Model):
    match_number = models.AutoField(primary_key=True, unique=True)
    player = models.ForeignKey(Player,null=True, related_name='matches')
    date = models.DateTimeField()
    #weather = models.ForeignKey(WeatherConditions, null = True, blank = True)
    user = models.ForeignKey(User, default=1)

    def __unicode__(self):
        return u'%i' % self.match_number
    def get_absolute_url(self):
        return reverse('Match_detail',kwargs={'pk':self.pk,'pkr':self.player.number_of_player})

class Throw (models.Model):
    #code = models.AutoField(primary_key=True, unique=True)
    hole = models.ForeignKey(Hole,null=True, related_name='throws')
    match = models.ForeignKey(Match,null=True, related_name='throws')
    score = models.IntegerField( null = False, blank = False)
    user = models.ForeignKey(User, default=1)

    def __unicode__(self):
        return u'Hole: %s, Match: %s' % (self.hole.id, self.match.match_number)
    def get_absolute_url(self):
        return reverse('Match_detail',kwargs={'pkr':self.match.player.number_of_player,'pk':self.match.match_number})

BePitchAndPutt/iBePitchAndPutt/forms.py
from django.forms import ModelForm
from models import Player, Match, Throw

class PlayerForm(ModelForm):
	class Meta:
		model = Player
		exclude = ('number_of_player','user')

class MatchForm(ModelForm):
    class Meta:
        model = Match
        exclude = ('match_number','user')

class ThrowForm(ModelForm):
	class Meta:
		model = Throw
		exclude = ('code','match','user')

BePitchAndPutt/iBePitchAndPutt/views.py
from django.shortcuts import render, render_to_response

from django.http import HttpResponse, Http404
from django.template import Context
from django.template.loader import get_template
from django.views.generic import DetailView, ListView
from django.contrib.auth.models import User
from django.utils import timezone

from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.core import serializers
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from django.views.generic.base import TemplateResponseMixin
from django.views.generic.edit import CreateView, UpdateView

from django.views.generic.base import TemplateResponseMixin
from django.views.generic.edit import CreateView, UpdateView


from rest_framework import generics, permissions
from rest_framework.permissions import IsAuthenticatedOrReadOnly

from models import Player, Field, Hole, Match, Throw 
from serializers import PlayerSerializer, FieldSerializer, MatchSerializer, ThrowSerializer
from forms import *




class ConnegResponseMixin(TemplateResponseMixin):

    def render_json_object_response(self, objects, **kwargs):
        json_data = serializers.serialize(u"json", objects, **kwargs)
        return HttpResponse(json_data, content_type=u"application/json")

    def render_xml_object_response(self, objects, **kwargs):
        xml_data = serializers.serialize(u"xml", objects, **kwargs)
        return HttpResponse(xml_data, content_type=u"application/xml")

    def render_to_response(self, context, **kwargs):
        if 'extension' in self.kwargs:
            try:
                objects = [self.object]
            except AttributeError:
                objects = self.object_list
            if self.kwargs['extension'] == 'json':
                return self.render_json_object_response(objects=objects)
            elif self.kwargs['extension'] == 'xml':
                return self.render_xml_object_response(objects=objects)
        return super(ConnegResponseMixin, self).render_to_response(context)

class LoginRequiredMixin(object):
    @method_decorator(login_required())
    def dispatch(self, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(*args, **kwargs)

class CheckIsOwnerMixin(object):
    def get_object(self, *args, **kwargs):
        obj = super(CheckIsOwnerMixin, self).get_object(*args, **kwargs)
        if not obj.user == self.request.user:
            raise PermissionDenied
        return obj

class LoginRequiredCheckIsOwnerUpdateView(LoginRequiredMixin, CheckIsOwnerMixin, UpdateView):
    template_name = 'form.html'

def mainpage(request):
    return render_to_response(

    'Mainpage.html',
    {
        'titlehead': 'BePitchAndPutt app',
        'pagetitle': 'Benvingut a BePitchAndPutt app',
        'contentbody': 'La millor aplicacio per guardar els resultats dels teus entrenaments',
        'user': request.user
    })

class PlayerList (ListView):
    model = Player
    queryset = Player.objects.all()
    context_object_name='Player_list'
    template_name='Player.html'

class FieldList (ListView):
    model = Field
    queryset = Field.objects.all()
    context_object_name='Field_list'
    template_name='Field.html'

class PlayerDetail(DetailView):
    model = Player
    template_name = 'Player_info.html' 

    def get_context_data(self, **kwargs):
        context = super(PlayerDetail, self).get_context_data(**kwargs)
        return context


class PlayerCreate(LoginRequiredMixin, CreateView):
    model = Player
    template_name = 'form.html'
    form_class = PlayerForm
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(PlayerCreate, self).form_valid(form)

class MatchDetail(DetailView):
    model = Match
    template_name = 'Match_info.html'   
    def get_context_data(self, **kwargs):
        context = super(MatchDetail, self).get_context_data(**kwargs)
        return context


class MatchCreate(LoginRequiredMixin,CreateView):
    model = Match
    template_name = 'form.html'
    form_class = MatchForm
    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.player = get_object_or_404(Player, pk=self.kwargs['pk'])
        return super(MatchCreate, self).form_valid(form)


class ThrowDetail(DetailView):
    model = Throw
    template_name = 'Throw_info.html'
    def get_context_data(self, **kwargs):
        context = super(ThrowDetail, self).get_context_data(**kwargs)
        return context

class ThrowCreate(LoginRequiredMixin,CreateView):
    model = Throw
    template_name = 'form.html'
    form_class = ThrowForm
    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.match = get_object_or_404(Match, pk=self.kwargs['pk'])
        return super(ThrowCreate, self).form_valid(form)

class FieldDetail(DetailView):
    model = Field
    template_name = 'Field_info.html'   
    def get_context_data(self, **kwargs):
        context = super(FieldDetail, self).get_context_data(**kwargs)
        return context

class HoleDetail(DetailView):
    model = Hole
    template_name = 'Hole_info.html'   
    def get_context_data(self, **kwargs):
        context = super(HoleDetail, self).get_context_data(**kwargs)
        return context

def rules (request):
    return render_to_response(

    'Rules.html',
    {
        'titlehead': 'Rules',
        'pagetitle':'Ultima versio de les normes',
        
    })

#RESTful API


class IsOwnerOrReadOnly(permissions.IsAuthenticatedOrReadOnly):

    def has_object_permission(self, request, view, obj):
        # Read permissions are allowed to any request,
        # so we'll always allow GET, HEAD or OPTIONS requests.
        if request.method in permissions.SAFE_METHODS:
            return True
        # Instance must have an attribute named `owner`.
        return obj.user == request.user


class APIPlayerList(generics.ListCreateAPIView):
    permission_classes = (IsAuthenticatedOrReadOnly,)
    model = Player
    queryset = Player.objects.all()
    serializer_class = PlayerSerializer

class APIPlayerDetail(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = (IsOwnerOrReadOnly,)
    model = Player
    queryset = Player.objects.all()
    serializer_class = PlayerSerializer

class APIFieldList(generics.ListCreateAPIView):
    permission_classes = (IsAuthenticatedOrReadOnly,)
    model = Field
    queryset = Field.objects.all()
    serializer_class = FieldSerializer

class APIFieldDetail(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = (IsOwnerOrReadOnly,)
    model = Field
    queryset = Field.objects.all()
    serializer_class = FieldSerializer


class APIMatchDetail(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = (IsOwnerOrReadOnly,)
    model = Match
    queryset = Match.objects.all()
    serializer_class = MatchSerializer

class APIThrowDetail(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = (IsOwnerOrReadOnly,)
    model = Throw
    queryset = Throw.objects.all()
    serializer_class = ThrowSerializer

BePitchAndPutt/iBePitchAndPutt/templates/Basepage.html
<html>
  <head>
  <title>{{ titlehead}}</title>
  </head>
<body>
  <h1>{{ pagetitle }}</h1>
{% block content %}
{% endblock %}
</body>
</html>

BePitchAndPutt/iBePitchAndPutt/templates/Field.html
{% extends 'basepage.html' %}
{% block content %}
<ul>
  {%for field in Field_list%}
  <li>
    <a href="{% url 'Field_detail'  field.id %}"> {{field.field_name}}</a>
  </li>
  {%endfor%}
</ul>

{% endblock %}

BePitchAndPutt/iBePitchAndPutt/templates/Field_info.html
{% extends 'basepage.html' %}
{% block content %}

<span vocab="http://schema.org" typeof="GolfCourse">
  <h1><span property="name">{{field.field_name}}</span></h1>
  <div property="address" typeof="PostalAddress">
    <h2> Adreça i contacte: </h2>
    <span property="streetAddress">Carrer: {{field.street}}<br></span>
    <span property="addressLocality">Ciutat: {{field.city}}</span><br>
    <span property="addressRegion">País: {{field.stateOrProvince}}</span><br>
    <span property="postalCode">Codi postal: {{field.zipCode}}</span><br>
    <span property="telephone">Telèfon: {{field.telephone}}</span><br>
    URL: {{field.url}}<br>
  </div>
  <div>
    <h2> Especificacions tècniques: </h2>
    Codi del camp: {{field.FieldCode}}<br>
    Número de forats: {{field.number_of_holes}}<br>
    Par: {{field.par}}<br>
  </div>

  <div>
  <ul>
  <table border=1 cellpadding=10>
    <th>Forat</th>
    {%for hole in field.holes.all %}
      <th>{{hole.hole_number}}</th>
    {%endfor%}

  <tr>
    <td><strong>Metres</strong></td>
      {% for hole in field.holes.all %}
        <td>{{hole.meters}}</td>
      {%endfor%}
  </tr>

  <tr>
    <td><strong>Handicap</strong></td>
      {% for hole in field.holes.all %}
        <td>{{hole.handicap_hole}}</td>
      {%endfor%}
  </tr>

  </table>
  </ul>
</div>
{% endblock %}

BePitchAndPutt/iBePitchAndPutt/templates/Mainpage.html
{% extends "basepage.html" %}
{% block content %}
{% if user.username %}
<p>Benvingut {{ user.username }},
la teva aplicació de Pitch And Putt esta a punt!
Ja pots registrar els teus resultats!
  <li>
    <a href="{% url 'Player_list' %}"> {{'Jugadors'}}</a>
  </li>
    <li>
    <a href="{% url 'Field_list' %}"> {{'Camps de Pitch And Putt'}}</a>
  </li>
    <li>
    <a href="{% url 'rules' %}"> {{'Normes'}}</a>
  </li>
</p>
{% else %}
<p>Benvingut anònim:
T'has de  <a href="/login/">registrar</a>
per guardar els teus resultats.</p>
{% endif %}
{% endblock %}

BePitchAndPutt/iBePitchAndPutt/templates/Match_info.html
{% extends 'basepage.html' %}
{% block content %}

  <p>
    Match number: {{match.match_number}}<br>
    Player: {{match.player}}<br>
    Date: {{match.date}}<br>
  </p>
  <p>
  Throws
  {% if user.is_authenticated %}(<a href="{%url 'throw_create' match.player.number_of_player match.match_number%}" > Create new throw </a>){% endif %}
  </p>

  <p>
    {% if user == match.user %}
        (<a href="{% url 'match_edit' match.player.number_of_player match.match_number %}">Edit match</a>)
    {% endif %}
  </p>
 
  <table border=1 cellpadding=10>


    <th>Forat</th>
    {%for throw in match.throws.all %}
      <th><a href="{%url 'throw_edit' match.player.number_of_player match.match_number  throw.id %}" >{{throw.hole.hole_number}}</a></th>
    {%endfor%}

  <tr>
    <td><strong>Puntuació</strong></td>
      {% for throw in match.throws.all %}
        <td>{{throw.score}} </td>
      {%endfor%}
  </tr>

  </table>

{% endblock %}

BePitchAndPutt/iBePitchAndPutt/templates/Player.html
{% extends 'basepage.html' %}
{% block content %}

<h1>
	Players
	{% if user.is_authenticated %}(<a href="{%url 'player_create' %}" > Create new player </a>){% endif %}

</h1>
<p>
<ul>
  {%for player in Player_list %}
  	<li><a href="{% url 'Player_detail'  player.number_of_player %}"> 
    {{player.name}}</a>
  </li>
  {%endfor%}
</ul>
</p>
{% endblock %}

BePitchAndPutt/iBePitchAndPutt/templates/Player_info.html
{% extends 'basepage.html' %}
{% block content %}
<span vocab = "http://shema.org" typeof="Person">
<h1>Informació del jugador</h1>
<div>
<h2><span property="name">{{player.name}}<br>
Nº de jugador: {{player.number_of_player}}</h2>
<div>    
    <span property="birthDate"> Data de naixement: {{player.birthdate}}<br>
    <span property="address" typeof="PostalAddress">
    <span property="addressCountry"> País: {{player.country}}<br>
    <span property="addressRegion"> Estat: {{player.stateOrProvince}}<br>
    <span property="addressLocality"> Ciutat: {{player.city}}<br>
    <span property="streetAddres"> Adreça: {{player.street}}<br>
    <span property="postalCode"> Codi postal: {{player.zipCode}}<br>
    <span poperty="telephone"> Telèfon: {{player.telephone}}<br>
    Handicap: {{player.handicap}}<br>
  <div>
  <ul>
    {% for match in player.matches.all %}

        <li><a href="{% url 'Match_detail' player.number_of_player match.match_number %}">
            {{ match.pk }} -- {{ match.date }}</a></li>
    {% empty %}<li>Sorry, no matches for this player yet.</li>
    {% endfor %}
  </ul>
  </div>
  <div>
  Matches
  {% if user.is_authenticated %}(<a href="{%url 'match_create' player.number_of_player%}" > Create new match </a>){% endif %}
  </div>
{% endblock %}

BePitchAndPutt/iBePitchAndPutt/templates/Rules.html
{% extends 'basepage.html' %}
{% block content %}

<div>
<object data="http://nova.pitch.cat/media/annexes/image_9932_1.pdf" width="100%" height="1200px">
  <embed wmode="transparent" src="http://nova.pitch.cat/media/annexes/image_9932_1.pdf" />
  Error: Embedded data could not be displayed.
</object>
</div>
{% endblock %}

BePitchAndPutt/iBePitchAndPutt/templates/Throw_info.html
{% extends 'basepage.html' %}
{% block content %}

  <h1>{{field.field_name}}</h1>
  <p>
    Forat: {{throw.hole}}<br>
    Puntuació: {{throw.score}}<br>
  </p>

   <p>
    {% if user == match.user %}
        (<a href="{% url 'throw_edit' throw.id %}">Edita tirada</a>)
    {% endif %}
  </p>
{% endblock %}

BePitchAndPutt/iBePitchAndPutt/templates/WeatherConditions.html
{% extends 'basepage.html' %}
{% block content %}
  <p>
    WindSpeed: {{weather.windSpeed}}<br>
    WindDirection: {{weather.windDirection}}<br>
  </p>
{% endblock %}

BePitchAndPutt/iBePitchAndPutt/templates/basepage.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery­‐ui.css" />
    <link rel="stylesheet" href="{% static "style/base.css" %}" />
    <script src="https://code.jquery.com/jquery-2.2.3.min.js"></script>
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
  	<title>{{ titlehead}}</title>
  </head>
  <body>
  <div id="header">
    <span style="float:right">
    {% block header %}
        {% if user.username %}
            <p>User: {{ user.username }} | <a href="{% url 'logout' %}?next={{request.path}}">logout</a></p>
        {% else %}
            <p><a href="{% url 'login' %}?next={{request.path}}">login</a></p>
        {% endif %}
    {% endblock %}
    </span>
      <a href="javascript:history.back(-1);" title="Enrere">Enrere</a>
      <a href="{% url 'home' %}">Inici</a>

  </div>

	<h1>{{ pagetitle }}</h1> 
	{% block content %}
	{% endblock %}
   </body>
</html>

BePitchAndPutt/iBePitchAndPutt/templates/form.html
{% extends "basepage.html" %}
{% load staticfiles %}
{% block content %}
    <script>
        $(function() {
            $.getJSON("{% static "handicap.json" %}", {}, function (handicap) {
                $("#id_handicap").autocomplete({
                    source: handicap
                });
            });
            $("#id_city").autocomplete({
                source: function( request, response ) {
                    $.ajax({
                        url: "http://ws.geonames.org/searchJSON",
                        dataType: "jsonp",
                        data: {
                            featureClass: "P",
                            maxRows: 10,
                            name_startsWith: request.term,
                            username: "demo"
                        },
                        success: function( data ) {
                            response( $.map( data.geonames, function( item ) {
                                return {
                                    label: item.name + (item.adminName1 ? ", " + item.adminName1 : "") + ", " + item.countryName,
                                    value: item.name,
                                    stateOrProvince: item.adminName1,
                                    countryName: item.countryName
                                }
                            }));
                        }
                    });
                },
                minLength: 2,
                select: function( event, ui ) {
                    if (ui.item) {
                        $("#id_stateOrProvince").val(ui.item.stateOrProvince);
                        $("#id_country").val(ui.item.countryName);
                        $("#id_zipCode").val("");
                    }
                }
            });
        });
    </script>
    <form method="post" enctype="multipart/form-data" action="">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit"/>
    </form>
{% endblock %}